// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ESPD35

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image5, &ui_img_wp1862222_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 30);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Controll elements");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Screen5);
    lv_dropdown_set_options(ui_Dropdown1, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -145);
    lv_obj_set_y(ui_Dropdown1, 0);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Roller1 = lv_roller_create(ui_Screen5);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 135);
    lv_obj_set_y(ui_Switch1, 50);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 135);
    lv_obj_set_y(ui_Switch2, 0);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Switch3 = lv_switch_create(ui_Screen5);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 135);
    lv_obj_set_y(ui_Switch3, -50);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
